-- DELETE apaga registros da tabela
-- NÃO use DELETE SEM WHERE BROTHER

DELETE FROM users WHERE id = 113;

-- SEMPRE USE SELECT PARA GARANTIR QUE ESTÁ APAGANDO O REGISTRO CERTO

SELECT * FROM users WHERE id BETWEEN 110 and 120;